name: Rusty Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, universal2-apple-darwin]
    runs-on: ubuntu-latest
    container: messense/cargo-zigbuild:0.18
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cargo zigbuild --target ${{ matrix.target }} --release
      
      - name: Conditional Step
        if: matrix.target == 'universal2-apple-darwin'
        uses: indygreg/apple-code-sign-action@v1
        with: 
          input_path: target/universal2-apple-darwin/release/rusty
          p12_file: cert.p12
          p12_password: ${{ secrets.PASSWORD }}

      - name: Archive
        run: |
          dirname="rusty-${{ github.event.inputs.version }}-${{ matrix.target }}"
          mkdir "$dirname"
          mv "target/${{ matrix.target }}/release/rusty" "$dirname"
          tar -czf "$dirname.tar.gz" "$dirname"
          echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          files: |
            ${{ env.ASSET }}
