name: Rusty Build

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, universal2-apple-darwin]
    runs-on: ubuntu-latest
    container: messense/cargo-zigbuild:0.18
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cargo zigbuild --target ${{ matrix.target }} --release

      - name: Archive
        run: |
          dirname="rusty-${{ github.ref }}-${{ matrix.target }}"
          mkdir "$dirname"
          mv "target/${{ matrix.target }}/release/rusty" "$dirname"          
          tar -czf "$dirname.tar.gz" "$dirname"
          echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
